package com.smartcampus.backend.model;

public enum TicketAssistantIntent {
    CHECK_MY_TICKETS,
    CHECK_LATEST_TICKET_STATUS,
    CHECK_ASSIGNED_TECHNICIAN,
    CHECK_SLA,
    CHECK_OVERDUE_TICKETS,
    CHECK_OPEN_TICKETS,
    CHECK_URGENT_TICKETS,
    CHECK_UNASSIGNED_TICKETS,
    CHECK_ASSIGNED_TICKETS,
    CHECK_LATEST_COMMENTS,
    CHECK_SLA_SUMMARY,
    CHECK_NEXT_VALID_STATUS,
    HELP_CREATE_TICKET,
    HELP_ATTACHMENTS,
    HELP_STATUS_MEANING,
    UNKNOWN
}
